# Generated by Django 5.1.1 on 2024-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('compmpany_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Type', models.CharField(choices=[('IT', 'IT'), ('Banking', 'Banking'), ('Services', 'Services')], max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
