# Generated by Django 5.1.1 on 2024-09-17 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APi_App', '0002_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Salary', models.IntegerField(max_length=100)),
                ('position', models.CharField(choices=[('SoftWare Developer', 'SoftWare Developer'), ('Accounts', 'Accounts'), ('Sales', 'Sales'), ('Manager', 'Manager'), ('Project Manager', 'Project Manager'), ('Team Leader', 'Team Leader')], max_length=100)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APi_App.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
