# Generated by Django 5.1.1 on 2024-09-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APi_App', '0003_employee_delete_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Salary',
            field=models.IntegerField(),
        ),
    ]
