# Generated by Django 5.1.1 on 2024-09-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APi_App', '0004_alter_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='list_of_pieces',
            field=models.JSONField(default=' '),
            preserve_default=False,
        ),
    ]
