# Generated by Django 5.1.1 on 2024-09-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APi_App', '0005_company_list_of_pieces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='list_of_pieces',
        ),
    ]
